setwd("C:/Users/usuario/Repos/beca-dit")


library(devtools)
library(jsonlite)
library(Hmisc)
library(dbscan)
library(arules)
library(arulesSequences)
library(vcd)
library(ggplot2)
#install.packages("dbscan")
#library(dbscan)
library(opencpu)
#install.packages("devtools")
opencpu$stop()
install("findAllJointAnomalies")
opencpu$start(5307)